### ISSUE TITLE
PromptAdapterPath and LoRAModulePath

### ISSUE THREAD

**Issue by torsteinelv** [sasha0552/pascal-pkgs-ci#7]
hello, getting problems importing PromptAdapterPath and LoRAModulePath?
```
`apiVersion: ray.io/v1
kind: RayService
metadata:
  name: vllm-test
  namespace: ray-operator
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path: ray-serve.vllm_engine:build_app
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_cpus: 2
      runtime_env:
        working_dir: "https://github.com/torsteinelv/ray-serve/archive/refs/heads/main.zip"
        pip: ["ray[serve]", "requests"]
      env:
        - name: CUDA_LAUNCH_BLOCKING
          value: 1
        - name: TORCH_USE_CUDA_DSA
          value: 1
      args:
        model: microsoft/Phi-3-mini-128k-instruct
        dtype: float16
        pipeline-parallel-size: 3
        gpu_memory_utilization: 0.7
        trust_remote_code: None
        max-model-len: 1024
  rayClusterConfig:
    headGroupSpec:
      serviceType: LoadBalancer
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          volumes:
            - name: model-storage
              persistentVolumeClaim:
                claimName: vllm-test-models
          containers:
          - name: ray-head
            image: ghcr.io/sasha0552/vllm:latest
            resources:
              limits:
                cpu: "4"
                memory: "8Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "1"
                memory: "1Gi"
                nvidia.com/gpu: "1"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            volumeMounts:
              - mountPath: /models
                name: model-storage
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: ray.io/node-type
                    operator: In
                    values:
                    - worker
                topologyKey: "kubernetes.io/hostname"
    workerGroupSpecs:
    - replicas: 2
      minReplicas: 0
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          volumes:
            - name: model-storage
              persistentVolumeClaim:
                claimName: vllm-test-models
          containers:
          - name: llm
            image: ghcr.io/sasha0552/vllm:latest
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            resources:
              limits:
                cpu: "4"
                memory: "8Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "1"
                memory: "1Gi"
                nvidia.com/gpu: "1"
            volumeMounts:
              - mountPath: /models
                name: model-storage
          tolerations:
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: ray.io/node-type
                    operator: In
                    values:
                    - worker
                topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-test-models
  namespace: ray-operator
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi`
```

```
`from typing import Dict, Optional, List
import logging

from fastapi import FastAPI
from starlette.requests import Request
from starlette.responses import StreamingResponse, JSONResponse

from ray import serve

from vllm.engine.arg_utils import AsyncEngineArgs
from vllm.engine.async_llm_engine import AsyncLLMEngine
from vllm.entrypoints.openai.cli_args import make_arg_parser
from vllm.entrypoints.openai.protocol import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ErrorResponse,
)
from vllm.entrypoints.openai.serving_chat import OpenAIServingChat
#from vllm.entrypoints.openai.serving_engine import LoRAModulePath, PromptAdapterPath
from vllm.utils import FlexibleArgumentParser
from vllm.entrypoints.logger import RequestLogger
logger = logging.getLogger("ray.serve")

app = FastAPI()


@serve.deployment(name="VLLMDeployment")
@serve.ingress(app)
class VLLMDeployment:
    def __init__(
        self,
        engine_args: AsyncEngineArgs,
        response_role: str,
#        lora_modules: Optional[List[LoRAModulePath]] = None,
#        prompt_adapters: Optional[List[PromptAdapterPath]] = None,
        request_logger: Optional[RequestLogger] = None,
        chat_template: Optional[str] = None,
    ):
        logger.info(f"Starting with engine args: {engine_args}")
        self.openai_serving_chat = None
        self.engine_args = engine_args
        self.response_role = response_role
#        self.lora_modules = lora_modules
#        self.prompt_adapters = prompt_adapters
        self.request_logger = request_logger
        self.chat_template = chat_template
        self.engine = AsyncLLMEngine.from_engine_args(engine_args)

    @app.post("/v1/chat/completions")
    async def create_chat_completion(
        self, request: ChatCompletionRequest, raw_request: Request
    ):
        """OpenAI-compatible HTTP endpoint.

        API reference:
            - https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
        """
        if not self.openai_serving_chat:
            model_config = await self.engine.get_model_config()
            # Determine the name of the served model for the OpenAI client.
            if self.engine_args.served_model_name is not None:
                served_model_names = self.engine_args.served_model_name
            else:
                served_model_names = [self.engine_args.model]
            self.openai_serving_chat = OpenAIServingChat(
                self.engine,
                model_config,
                served_model_names,
                self.response_role,
#                lora_modules=self.lora_modules,
                prompt_adapters=self.prompt_adapters,
                request_logger=self.request_logger,
                chat_template=self.chat_template,
            )
        logger.info(f"Request: {request}")
        generator = await self.openai_serving_chat.create_chat_completion(
            request, raw_request
        )
        if isinstance(generator, ErrorResponse):
            return JSONResponse(
                content=generator.model_dump(), status_code=generator.code
            )
        if request.stream:
            return StreamingResponse(content=generator, media_type="text/event-stream")
        else:
            assert isinstance(generator, ChatCompletionResponse)
            return JSONResponse(content=generator.model_dump())


def parse_vllm_args(cli_args: Dict[str, Optional[str]]):
    
    # Opprett parser
    parser = FlexibleArgumentParser(description="vLLM CLI")
    parser = make_arg_parser(parser)
    
    arg_strings = []
    for key, value in cli_args.items():
        logger.info(f"Processing argument: --{key} with value: {value}")
        
        if value is True:  # Håndter boolske flagg satt til True
            arg_strings.append(f"--{key}")
        elif value not in (None, "None"):  # Ignorer None eller 'None' som streng
            arg_strings.extend([f"--{key}", str(value)])
        else:
            arg_strings.append(f"--{key}")

    parsed_args = parser.parse_args(args=arg_strings)
    
    return parsed_args

def build_app(cli_args: Dict[str, Optional[str]]) -> serve.Application:
    parsed_args = parse_vllm_args(cli_args)
    engine_args = AsyncEngineArgs.from_cli_args(parsed_args)
    engine_args.worker_use_ray = True
    
    return VLLMDeployment.bind(
        engine_args,
        parsed_args.response_role,
        cli_args.get("request_logger"),
        parsed_args.chat_template,
    )`
```
